  - name: Single Shot
    damage: 10
    reloadTimeSeconds: 0.5
    lifespanSeconds: 2
    spritePath: /path/to/sprite

  - name: Double Shot
    damage: 20
    reloadTimeSeconds: 0.8
    lifespanSeconds: 2
    spritePath: /path/to/sprite